{
 "title": "Center 2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CENTER 2",
   "type": "geomap",
   "description": "Lloc on es troba situat el Centre i si es situa damunt el punt es poden observar els sensors que conté.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "º" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT * FROM iotib2.centros where Name = \"Center 2\" "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 0 },
   "options": {
    "content": "# <center>**ACTUAL ENVIRONMENTAL MONITORING**</center>\n\n\n"
   },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where milesight_payload.Tipo_dec = '01' order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "Mesura el percentatge de temps en què detecta presència en un rang de 8 m.",
   "gridPos": { "h": 2, "w": 7, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select presence from adeunis_payload join data on data.id = adeunis_payload.id where FormatType = \"5C\" and data.dev_eui =\"00-18-b2-60-00-00-04-7f\" order by trx_time desc limit 1;"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select humidity from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-78-5d-12-43-02\" order by trx_time desc limit 1"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "Mesura subjectiva representativa de la percepció humana expressada com al 100% de llum",
   "gridPos": { "h": 2, "w": 7, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select luminosity from adeunis_payload join data on data.id = adeunis_payload.id where FormatType = \"5C\" and data.dev_eui =\"00-18-b2-60-00-00-04-7f\" order by trx_time desc limit 1;"
    }
   ]
  },
  {
   "title": "Motion_Sensor",
   "type": "stat",
   "description": "Avisa si el sensor ha detectat moviment, i avisa quan deixa de detectarlo.",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select AlarmState,PresenceState from adeunis_payload join data on data.id = adeunis_payload.id where (FormatType = \"5D\" or FormatType =\"5C\") and data.dev_eui =\"00-18-b2-60-00-00-04-7f\" order by trx_time desc limit 1;"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select temperature from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-78-5d-12-43-02\" order by trx_time desc limit 1;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 8 },
   "options": { "content": "# **DEVICE BATTERY**\n\n" },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where milesight_payload.Tipo_dec = '01' order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 8 },
   "options": {
    "content": "# <center>**ENVIRONMENTAL MONITORING CHARTS**</center>\n\n"
   },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where milesight_payload.Tipo_dec = '01' order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where tipo_dec = '01' and dev_eui =\"24-e1-24-78-5d-12-43-02\" order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Indoor_Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select trx_time, humidity from data join milesight_payload on data.id = milesight_payload.id  where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-78-5d-12-43-02\""
    }
   ]
  },
  {
   "title": "Indoor_Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select trx_time, temperature from data join milesight_payload on data.id = milesight_payload.id  where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-78-5d-12-43-02\""
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 12 },
   "options": { "content": "# **LOST PACKAGES**\n\n" },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where milesight_payload.Tipo_dec = '01' order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Indoor_Motion_Sensor",
   "type": "barchart",
   "description": "Calcul de paquets perduts, del detector de presència interior, de cada mes, limitant-se als 6 darrers mesos.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "hist",
     "rawSql": "SELECT porcentajePaquetesPerdidos,periodo FROM iotib2.paquetesperdidos where dev_eui = \"00-18-b2-60-00-00-04-7f\" limit 6"
    }
   ]
  },
  {
   "title": "Indoor_Presence",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select trx_time,presence from adeunis_payload join data on data.id = adeunis_payload.id where FormatType = \"5C\" and data.dev_eui =\"00-18-b2-60-00-00-04-7f\" order by trx_time desc ;"
    }
   ]
  },
  {
   "title": "Indoor_Luminosity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select trx_time,luminosity from adeunis_payload join data on data.id = adeunis_payload.id where FormatType = \"5C\" and data.dev_eui =\"00-18-b2-60-00-00-04-7f\" order by trx_time desc ;"
    }
   ]
  },
  {
   "title": "Indoor_Temperature_Humidity_Sensor",
   "type": "barchart",
   "description": "Calcul de paquets perduts, del medidor de temperatura i humitat interior, de cada mes, limitant-se als 6 darrers mesos.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "hist",
     "rawSql": "SELECT porcentajePaquetesPerdidos,periodo FROM iotib2.paquetesperdidos where dev_eui = \"24-e1-24-78-5d-12-43-02\" limit 6"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "# <center>**NETWORK**</center>\n\n"
   },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where milesight_payload.Tipo_dec = '01' order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Data_Rate",
   "type": "piechart",
   "description": "Descriu el percentatge de les diferents taxes de transmissió dels uplinks de tots els  medidors que hi ha al centre.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT data_rate,count(data_rate) from data where (dev_eui = \"00-18-b2-60-00-00-04-7f\" or dev_eui = \"24-e1-24-78-5d-12-43-02\") and direction = \"up\" and port != '0' GROUP BY data_rate"
    }
   ]
  },
  {
   "title": "SNR",
   "type": "timeseries",
   "description": "Relació senyal-soroll de les senyals transmeses pels uplinks dels dispositius del centre.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT trx_time,SNR FROM data where (dev_eui = \"00-18-b2-60-00-00-04-7f\" or dev_eui = \"24-e1-24-78-5d-12-43-02\") and direction =\"up\" and  port != '0' "
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "description": "Detecta presència en detectar moviment i com més a prop del dispositiu estigui, major serà el valor que proporcioni el sensor i viceversa.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT trx_time,RSSI_UP FROM data where (dev_eui = \"24-e1-24-78-5d-12-43-02\" or dev_eui = \"00-18-b2-60-00-00-04-7f\") and direction =\"up\" and  port != '0' "
    }
   ]
  }
 ]
}