{
 "title": "Center 1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CENTER 1",
   "type": "geomap",
   "description": "Lloc on es troba situat el Centre i si es situa damunt el punt es poden observar els sensors que conté.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "º" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT * FROM iotib2.centros where Name = \"Center 1\" "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 15, "x": 9, "y": 0 },
   "options": {
    "content": "# <center>**ACTUAL ENVIRONMENTAL MONITORING**</center>\n\n\n"
   },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where milesight_payload.Tipo_dec = '01' order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select temperature from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-8b-10-96-30\" order by trx_time desc limit 1;"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select humidity from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and (light != 0 and TVOC != 0 and Co2 != 0 and presure != 0) and data.dev_eui =\"24-e1-24-12-8b-10-96-30\" order by trx_time desc limit 1;"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select presure from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and (light != 0 and TVOC != 0 and Co2 != 0 and humidity != 0) and data.dev_eui =\"24-e1-24-12-8b-10-96-30\" order by trx_time desc limit 1;"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "Compostos Orgànics Volàtils Totals. Una categoria de compostos químics que poden evaporar-se fàcilment a temperatura ambient. Alguns, en concentracions elevades, poden ser perjudicials. Concretament més de 4000 ppb",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select TVOC from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and (light != 0 and humidity != 0 and Co2 != 0 and presure != 0) and data.dev_eui =\"24-e1-24-12-8b-10-96-30\" order by trx_time desc limit 1;"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select light from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and (humidity != 0 and TVOC != 0 and Co2 != 0 and presure != 0) and data.dev_eui =\"24-e1-24-12-8b-10-96-30\" order by trx_time desc limit 1;"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select Co2 from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and (light != 0 and TVOC != 0 and humidity != 0 and presure != 0) and data.dev_eui =\"24-e1-24-12-8b-10-96-30\" order by trx_time desc limit 1;"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT humidity FROM iotib2.sensecap_payload join data on data.id = sensecap_payload.id order by trx_time desc limit 1"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT temperature FROM iotib2.sensecap_payload join data on data.id = sensecap_payload.id order by trx_time desc limit 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 8 },
   "options": { "content": "#  **DEVICE BATTERY**\n\n" },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where milesight_payload.Tipo_dec = '01' order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Motion_Sensor",
   "type": "stat",
   "description": "Si el sensor detecta amoviment ens indicarà que hi ha presència , si deixà de detectarlo ens indicarà que no n'hi ha.",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.ValorPresencia,HayPresencia from data join milesight_payload ON data.ID = milesight_payload.ID where (Tipo_dec = '01' or Tipo_dec = '03') and devEui = \"24-e1-24-12-8b-10-96-30\" order by trx_time desc limit 1 ;"
    }
   ]
  },
  {
   "title": "Actual_Open_Door_Detection",
   "type": "stat",
   "description": "Alerta en el cas de que s'obri la porta i llavors mostra el seu estat.",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT ocStatus,ocNumber FROM iotib2.dragino_payload join data on data.id = dragino_payload.id  order by trx_time desc limit 1"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where milesight_payload.Tipo_dec = '01' and dev_eui=\"24-e1-24-12-8b-10-96-30\" order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT batteryLevel FROM iotib2.sensecap_payload join data on data.id = sensecap_payload.id WHERE uplinkInterval != 0 order by trx_time desc limit 1"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 17, "x": 7, "y": 12 },
   "options": {
    "content": "# <center>**ENVIRONMENTAL MONITORING CHARTS**</center>\n\n"
   },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where milesight_payload.Tipo_dec = '01' order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  Battery from data join dragino_payload ON data.ID = dragino_payload.ID where Model IS NOT NULL  order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Open_Door_Time",
   "type": "table",
   "description": "Indica l'instant i el temps en què la porta s'ha quedat oberta, si ha estat oberta més de 5 minuts (es visualitzen les 10 últimes vegades).",
   "gridPos": { "h": 7, "w": 12, "x": 10, "y": 14 },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT\r\n    trx_time,\r\n    lastOpen\r\nFROM (\r\n    SELECT\r\n        trx_time,\r\n        lastOpen,\r\n        LAG(lastOpen) over (ORDER BY trx_time asc) AS previous_lastOpen\r\n    FROM\r\n        iotib2.dragino_payload\r\n    JOIN\r\n        data ON data.id = dragino_payload.id\r\n        WHERE lastOpen > 5\r\n    ORDER BY\r\n        trx_time desc\r\n) AS subquery\r\nWHERE\r\n    lastOpen != previous_lastOpen OR previous_lastOpen IS NULL LIMIT 10;\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 16 },
   "options": { "content": "# **LOST PACKAGES**\n\n" },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where milesight_payload.Tipo_dec = '01' order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Indoor_Ambiance_Sensor",
   "type": "barchart",
   "description": "Calcul de paquets perduts, del medidor d'ambient interior, de cada mes, limitant-se als 6 darrers mesos.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "hist",
     "rawSql": "SELECT porcentajePaquetesPerdidos,periodo FROM iotib2.paquetesperdidos where dev_eui = \"24-e1-24-12-8b-10-96-30\" limit 6"
    }
   ]
  },
  {
   "title": "Indoor_Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select trx_time, humidity from data join milesight_payload on data.id = milesight_payload.id  where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-8b-10-96-30\""
    }
   ]
  },
  {
   "title": "Outdoor_Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT trx_time,humidity FROM iotib2.sensecap_payload join data on data.id = sensecap_payload.id "
    }
   ]
  },
  {
   "title": "Outdoor_Temperature_Humidity_Sensor",
   "type": "barchart",
   "description": "Calcul de paquets perduts, del medidor de temperatura i humitat exterior, de cada mes, limitant-se als 6 darrers mesos.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "hist",
     "rawSql": "SELECT porcentajePaquetesPerdidos,periodo FROM iotib2.paquetesperdidos where dev_eui = \"2c-f7-f1-c0-53-20-01-27\" limit 6"
    }
   ]
  },
  {
   "title": "Indoor_Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select trx_time, temperature from data join milesight_payload on data.id = milesight_payload.id  where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-8b-10-96-30\""
    }
   ]
  },
  {
   "title": "Outdoor_Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT trx_time,temperature FROM iotib2.sensecap_payload join data on data.id = sensecap_payload.id "
    }
   ]
  },
  {
   "title": "Door_Open_Sensor",
   "type": "barchart",
   "description": "Calcul de paquets perduts, del detector de portes obertes, de cada mes, limitant-se als 6 darrers mesos.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "hist",
     "rawSql": "SELECT porcentajePaquetesPerdidos,periodo FROM iotib2.paquetesperdidos where dev_eui = \"a8-40-41-f0-61-87-16-d5\" order by periodo desc limit 6"
    }
   ]
  },
  {
   "title": "Indoor_TVOC",
   "type": "timeseries",
   "description": "Compostos Orgànics Volàtils Totals. Una categoria de compostos químics que poden evaporar-se fàcilment a temperatura ambient. Alguns, en concentracions elevades, poden ser perjudicials. ",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select trx_time, TVOC from data join milesight_payload ON data.ID = milesight_payload.ID where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-8b-10-96-30\""
    }
   ]
  },
  {
   "title": "Indoor_Presence",
   "type": "timeseries",
   "description": "Detecta presencia al detectar movimiento y como más cerca del dispositivo esté mayor será el valor que propocione el sensor   y viceversa",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT Presence, trx_time FROM iotib2.milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-8b-10-96-30\""
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 39 },
   "options": { "content": "# **NETWORK**\n\n" },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where milesight_payload.Tipo_dec = '01' order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Data_Rate",
   "type": "piechart",
   "description": "Descriu el percentatge de les diferents taxes de transmissió dels uplinks de tots els  medidors que hi ha al centre.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT data_rate,count(data_rate) from data where (dev_eui = \"2c-f7-f1-c0-53-20-01-27\" or dev_eui = \"24-e1-24-12-8b-10-96-30\" or dev_eui=\"a8-40-41-f0-61-87-16-d5\") and direction = \"up\" and port != '0' GROUP BY data_rate"
    }
   ]
  },
  {
   "title": "Indoor_Luminosity",
   "type": "timeseries",
   "description": "El màxim poden ser 60000, però no ha passat els 150000",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select trx_time, light from data join milesight_payload ON data.ID = milesight_payload.ID where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-8b-10-96-30\""
    }
   ]
  },
  {
   "title": "Indoor_Presure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select trx_time, presure from data join milesight_payload ON data.ID = milesight_payload.ID where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-8b-10-96-30\""
    }
   ]
  },
  {
   "title": "SNR",
   "type": "timeseries",
   "description": "Relació senyal-soroll de les senyals transmeses pels uplinks dels dispositius del centre.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT trx_time,SNR FROM data where (dev_eui = \"2c-f7-f1-c0-53-20-01-27\" or dev_eui = \"24-e1-24-12-8b-10-96-30\" or dev_eui=\"a8-40-41-f0-61-87-16-d5\") and direction =\"up\" and  port != '0' "
    }
   ]
  },
  {
   "title": "Indoor_CO2_Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select trx_time, CO2 from data join milesight_payload ON data.ID = milesight_payload.ID where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-8b-10-96-30\"\r\n"
    }
   ]
  },
  {
   "title": "Open_Close_Door_%",
   "type": "piechart",
   "description": "Porcertantge de vegades que s'ha obert i tancat la porta.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT ocStatus, COUNT(ocStatus) \r\nFROM iotib2.dragino_payload \r\nWHERE ocStatus IS NOT NULL \r\nGROUP BY ocStatus;\r\n"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "description": "Potència del senyal rebut de les senyals transmeses dels upliks dels dispositius del centre.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT trx_time,RSSI_UP FROM data where (dev_eui = \"2c-f7-f1-c0-53-20-01-27\" or dev_eui = \"24-e1-24-12-8b-10-96-30\" or dev_eui=\"a8-40-41-f0-61-87-16-d5\") and direction =\"up\" and  port != '0' "
    }
   ]
  }
 ]
}