{
 "title": "Centre3",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CENTER 3",
   "type": "geomap",
   "description": "Lloc on es troba situat el Centre i si es situa damunt el punt es poden observar els sensors que conté.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "º" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT * FROM iotib2.centros where Name = \"Center 3\" "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 15, "x": 9, "y": 0 },
   "options": {
    "content": "# <center>**ACTUAL ENVIRONMENTAL MONITORING**</center>\n\n"
   },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where milesight_payload.Tipo_dec = '01' order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select temperature from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-6a-23-33-97\" order by trx_time desc limit 1;"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select presure from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-6a-23-33-97\" order by trx_time desc limit 1;"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select Co2 from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-6a-23-33-97\" order by trx_time desc limit 1;"
    }
   ]
  },
  {
   "title": "Detector de Presencia",
   "type": "stat",
   "description": "Avisa si el sensor ha detectat moviment, i avisa quan deixa de detectarlo.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.ValorPresencia,HayPresencia from data join milesight_payload ON data.ID = milesight_payload.ID where (Tipo_dec = '01' or Tipo_dec = '03') and devEui = \"24-e1-24-53-8d-05-17-44\" order by trx_time desc limit 1 ;"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select humidity from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-6a-23-33-97\" order by trx_time desc limit 1;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 8 },
   "options": { "content": "# **DEVICE BATTERY**\n\n" },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where milesight_payload.Tipo_dec = '01' order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 15, "x": 9, "y": 8 },
   "options": {
    "content": "# <center>**ENVIRONMENTAL MONITORING CHARTS**</center>\n\n"
   },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where milesight_payload.Tipo_dec = '01' order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where milesight_payload.Tipo_dec = '01' and dev_eui=\"24-e1-24-12-6a-23-33-97\" order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Outdoor_Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select trx_time, temperature from data join milesight_payload on data.id = milesight_payload.id  where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-6a-23-33-97\""
    }
   ]
  },
  {
   "title": "Outdoor_CO2_Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select trx_time, Co2 from data join milesight_payload on data.id = milesight_payload.id  where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-6a-23-33-97\""
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where milesight_payload.Tipo_dec = '01' and dev_eui=\"24-e1-24-53-8d-05-17-44\" order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 14 },
   "options": { "content": "# **LOST PACKAGES**\n\n" },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where milesight_payload.Tipo_dec = '01' order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Outdoor_Ambiance_Sensor",
   "type": "barchart",
   "description": "Calcul de paquets perduts, del medidor exterior, de cada mes, limitant-se als 6 darrers mesos.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "hist",
     "rawSql": "SELECT porcentajePaquetesPerdidos,periodo FROM iotib2.paquetesperdidos where dev_eui = \"24-e1-24-12-6a-23-33-97\" limit 6"
    }
   ]
  },
  {
   "title": "Outdoor_Presure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select trx_time, presure from data join milesight_payload on data.id = milesight_payload.id  where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-6a-23-33-97\""
    }
   ]
  },
  {
   "title": "Outdoor_Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select trx_time, humidity from data join milesight_payload on data.id = milesight_payload.id  where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-6a-23-33-97\""
    }
   ]
  },
  {
   "title": "Indoor_Motion_Sensor",
   "type": "barchart",
   "description": "Calcul de paquets perduts, del detector de presència interior, de cada mes, limitant-se als 6 darrers mesos.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "hist",
     "rawSql": "SELECT porcentajePaquetesPerdidos,periodo FROM iotib2.paquetesperdidos where dev_eui = \"24-e1-24-53-8d-05-17-44\" limit 6"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "# <center>**NETWORK**</center>\n\n"
   },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "select  milesight_payload.BatteryLevel from data join milesight_payload ON data.ID = milesight_payload.ID where milesight_payload.Tipo_dec = '01' order by trx_time desc limit 1;"
    },
    {
     "dataset": "iotib2",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Data_Rate",
   "type": "piechart",
   "description": "Mostra un gràfic de la relació senyal-soroll de les senyals transmeses pels tres dispositius.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT data_rate,count(data_rate) from data where (dev_eui = \"24-e1-24-12-6a-23-33-97\" or dev_eui = \"24-e1-24-53-8d-05-17-44\") and direction = \"up\" and port != '0' GROUP BY data_rate"
    }
   ]
  },
  {
   "title": "SNR",
   "type": "timeseries",
   "description": "Relació senyal-soroll de les senyals transmeses pels uplinks dels dispositius del centre.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT trx_time,SNR FROM data where (dev_eui = \"24-e1-24-12-6a-23-33-97\" or dev_eui = \"24-e1-24-53-8d-05-17-44\") and direction =\"up\" and  port != '0' "
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "description": "Potència del senyal rebut de les senyals transmeses dels upliks dels dispositius del centre.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "dataset": "iotib2",
     "rawSql": "SELECT trx_time,RSSI_UP FROM data where (dev_eui = \"24-e1-24-12-6a-23-33-97\" or dev_eui = \"24-e1-24-53-8d-05-17-44\" or dev_eui=\"a8-40-41-f0-61-87-16-d5\") and direction =\"up\" and  port != '0' "
    }
   ]
  }
 ]
}