{
 "title": "Principal",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CENTERS",
   "type": "geomap",
   "description": "Llocs on es troben situats tots els Centres i si es situa damunt el punt de qualsevol d'ells es poden observar els sensors que conté cada un.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "º" } },
   "targets": [
    { "dataset": "iotib2", "rawSql": "SELECT * FROM iotib2.centros;" }
   ]
  },
  {
   "title": "CENTER 1",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hist",
     "rawSql": "select temperature as Indoor_Temperature from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-8b-10-96-30\" order by trx_time desc limit 1;"
    },
    {
     "dataset": "hist",
     "rawSql": "select humidity as Indoor_Humidity from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and (light != 0 and TVOC != 0 and Co2 != 0 and presure != 0) and data.dev_eui =\"24-e1-24-12-8b-10-96-30\" order by trx_time desc limit 1;"
    },
    {
     "dataset": "hist",
     "rawSql": "SELECT ocStatus as Door_Open_Detector FROM iotib2.dragino_payload join data on data.id = dragino_payload.id  order by trx_time desc limit 1"
    },
    {
     "dataset": "hist",
     "rawSql": "SELECT temperature as Outdoor_Temperature FROM iotib2.sensecap_payload join data on data.id = sensecap_payload.id order by trx_time desc limit 1"
    },
    {
     "dataset": "hist",
     "rawSql": "SELECT humidity as Outdoor_Humidity FROM iotib2.sensecap_payload join data on data.id = sensecap_payload.id order by trx_time desc limit 1"
    },
    {
     "dataset": "hist",
     "rawSql": "select  milesight_payload.ValorPresencia as Indoor_Motion_Sensor from data join milesight_payload ON data.ID = milesight_payload.ID where (Tipo_dec = '01' or Tipo_dec = '03') and devEui = \"24-e1-24-12-8b-10-96-30\" order by trx_time desc limit 1 ;"
    }
   ]
  },
  {
   "title": "CENTER 2",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hist",
     "rawSql": "select temperature as Indoor_Temperature from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-78-5d-12-43-02\" order by trx_time desc limit 1;"
    },
    {
     "dataset": "hist",
     "rawSql": "select humidity as Indoor_Humidity from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-78-5d-12-43-02\" order by trx_time desc limit 1"
    },
    {
     "dataset": "hist",
     "rawSql": "select AlarmState as Indoor_Motion_Sensor from adeunis_payload join data on data.id = adeunis_payload.id where (FormatType = \"5D\" or FormatType =\"5C\") and data.dev_eui =\"00-18-b2-60-00-00-04-7f\" order by trx_time desc limit 1;"
    }
   ]
  },
  {
   "title": "CENTER 3",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hist",
     "rawSql": "select temperature as Outdoor_Temperature from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-6a-23-33-97\" order by trx_time desc limit 1;"
    },
    {
     "dataset": "hist",
     "rawSql": "select humidity as Outdoor_Humidity from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-6a-23-33-97\" order by trx_time desc limit 1"
    },
    {
     "dataset": "hist",
     "rawSql": "select  milesight_payload.ValorPresencia as Indoor_Motion_Sensor from data join milesight_payload ON data.ID = milesight_payload.ID where (Tipo_dec = '01' or Tipo_dec = '03') and devEui = \"24-e1-24-53-8d-05-17-44\" order by trx_time desc limit 1 ;"
    },
    {
     "dataset": "hist",
     "rawSql": "select presure as Outdoor_Presure from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-6a-23-33-97\" order by trx_time desc limit 1"
    },
    {
     "dataset": "hist",
     "rawSql": "select co2 as Outdoor_CO2_Level from milesight_payload join data on data.id = milesight_payload.id where (tipo_dec='01' or tipo_dec='03') and data.dev_eui =\"24-e1-24-12-6a-23-33-97\" order by trx_time desc limit 1"
    }
   ]
  }
 ]
}